// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnNUVAZPKcJytdsLvcnDDZgN1BLvq8muU',
    appId: '1:637251115626:android:f9fab1ab7572bc7e200813',
    messagingSenderId: '637251115626',
    projectId: 'stride-squad',
    databaseURL: 'https://stride-squad-default-rtdb.firebaseio.com',
    storageBucket: 'stride-squad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD889R__AcX-cDbBz2go1SuO8jtWS5lCCE',
    appId: '1:637251115626:ios:01b2859dcfa8d423200813',
    messagingSenderId: '637251115626',
    projectId: 'stride-squad',
    databaseURL: 'https://stride-squad-default-rtdb.firebaseio.com',
    storageBucket: 'stride-squad.appspot.com',
    iosClientId: '637251115626-kki7nefme53uvqb977eme9htsgh4h9u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.strideSquad',
  );
}
